//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workers.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Post { get; set; }
        public int PayCheck { get; set; }
    }
}
